.PHONY: clean All

All:
	@echo "----------Building project:[ Screen_Modelling_1 - Debug ]----------"
	@cd "Screen_Modelling_1" && $(MAKE) -f  "Screen_Modelling_1.mk"
clean:
	@echo "----------Cleaning project:[ Screen_Modelling_1 - Debug ]----------"
	@cd "Screen_Modelling_1" && $(MAKE) -f  "Screen_Modelling_1.mk" clean
