.PHONY: clean All

All:
	@echo "----------Building project:[ Cpp_Revision - Debug ]----------"
	@cd "Cpp_Revision" && $(MAKE) -f  "Cpp_Revision.mk"
clean:
	@echo "----------Cleaning project:[ Cpp_Revision - Debug ]----------"
	@cd "Cpp_Revision" && $(MAKE) -f  "Cpp_Revision.mk" clean
