.PHONY: clean All

All:
	@echo "----------Building project:[ Stop_Watch - Debug ]----------"
	@cd "Stop_Watch" && $(MAKE) -f  "Stop_Watch.mk"
clean:
	@echo "----------Cleaning project:[ Stop_Watch - Debug ]----------"
	@cd "Stop_Watch" && $(MAKE) -f  "Stop_Watch.mk" clean
